version: '2.4'

services:
  autoware-adapter:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/autoware-adapter:dcc
    container_name: autoware-adapter
    volumes:
      - ./config.ini:/autoware-adapter/config.ini
    network_mode: host
    ipc: host