version: '2.4'
services:
  cpm-generation:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/cpm-generation:latest
    restart: always
    volumes:
      - /services/cps/config.ini:/config.ini
    networks:
      deploymentslan:

  cpm-processing:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/cpm-processing:latest
    restart: always
    volumes:
      - /services/cps/config.ini:/config.ini
    networks:
      deploymentslan:

  radar-adapter:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/radar-adapter:latest
    restart: always
    volumes:
      - /services/cps/config.ini:/config.ini
    networks:
      deploymentslan:

  camera-adapter:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/camera-adapter:latest
    restart: always
    volumes:
      - /services/cps/config.ini:/config.ini
    networks:
      deploymentslan:

networks:
  deploymentslan:
    external: true
