version: '2.4'
services:
  radar-adapter:
    hostname: radar-adapter
    container_name: radar-adapter
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/radar-adapter:dcc-zenoh
    volumes:
      - ./config.ini:/config.ini
    network_mode: host
    ipc: host