# inventory/hosts.yml
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    prod:
      hosts:
        RSU:
          ansible_host: 127.0.0.1
          id: 0
          station_type: 15
          locator_latitude: 40.634724
          locator_longitude: -8.660401
          radar_adapter_count: 1
          camera_adapter_count: 1

        PIXKIT:
          ansible_host: 127.0.0.1
          id: 1
          station_type: 5
          processing_enable: false
          autoware_adapter_enable: true
          cps_overrides:
            generation:
              location_provider: dds
              dds_topic: vanetza/in/cam_full
              generation_dds_topic: vanetza/in/cpm # used to transmit CPMs using Vanetza

        HOLOLENS:
          ansible_host: 127.0.0.1
          id: 2
          station_type: 5
          camera_adapter_count: 1
          cps_overrides:
            generation:
              location_provider: mqtt
              mqtt_host: 127.0.0.1
              mqtt_port: 1883
              mqtt_topic: vanetza/in/vam
              generation_dds_topic: vanetza/in/cpm
            processing:
              location_provider: mqtt
              mqtt_host: 127.0.0.1
              mqtt_port: 1883
              mqtt_topic: vanetza/in/vam
            camera-adapter:
              mqtt_topic: jetson/hololens/tracking/objects

        BIKE:
          ansible_host: 127.0.0.1
          id: 3
          station_type: 5
          bike_adapter_enable: true
          cps_overrides:
            generation:
              location_provider: mqtt
              mqtt_host: 127.0.0.1
              mqtt_port: 1883
              mqtt_topic: vanetza/in/vam
              generation_dds_topic: vanetza/in/cpm
            processing:
              location_provider: mqtt
              mqtt_host: 127.0.0.1
              mqtt_port: 1883
              mqtt_topic: vanetza/in/vam

        