# inventory/hosts.yml
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    prod:
      hosts:
        RSU:
          ansible_host: 127.0.0.1
          id: 129
          station_type: 15
          locator_latitude: 40.634724
          locator_longitude: -8.660401
          radar_adapter_count: 1
          camera_adapter_count: 1

        PIX:
          ansible_host: 127.0.0.1
          id: 157
          station_type: 5
          processing_enable: false
          autoware_adapter_enable: true
          cps_overrides:
            generation:
              location_provider: dds
              dds_topic: vanetza/in/cam_full
              generation_dds_topic: vanetza/in/cpm
