version: '2.4'
services:
    cpm-processing:
        hostname: cpm-processing
        image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/cpm-processing:dev
        cap_add:
            - "NET_ADMIN"
        volumes:
            # - ./timing-data:/times
            - ./config.ini:/config.ini
        network_mode: host
        ipc: host
#         networks:
#             deploymentslan:

# networks:
#     deploymentslan:
#         external: true
