version: '2.4'
services:
  radar:
    hostname: radar
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/radar-adapter:latest
    cap_add:
      - "NET_ADMIN"
    volumes:
      - ./config.ini:/config.ini
    networks:
      vanetzalan0:
        ipv4_address: 192.168.98.41

networks:
  vanetzalan0:
    external: true