version: '2.4'
services:
  camera-adapter:
    hostname: camera-adapter
    container_name: camera-adapter
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/camera-adapter:dcc
    volumes:
      - ./config.ini:/config.ini
    network_mode: host
    ipc: host