// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file EncodedITSMessage.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ENCODEDITSMESSAGE_H_
#define _FAST_DDS_GENERATED_ENCODEDITSMESSAGE_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ENCODEDITSMESSAGE_SOURCE)
#define ENCODEDITSMESSAGE_DllAPI __declspec( dllexport )
#else
#define ENCODEDITSMESSAGE_DllAPI __declspec( dllimport )
#endif // ENCODEDITSMESSAGE_SOURCE
#else
#define ENCODEDITSMESSAGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ENCODEDITSMESSAGE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure EncodedITSMessage defined by the user in the IDL file.
 * @ingroup EncodedITSMessage
 */
class EncodedITSMessage
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport EncodedITSMessage();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~EncodedITSMessage();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object EncodedITSMessage that will be copied.
     */
    eProsima_user_DllExport EncodedITSMessage(
            const EncodedITSMessage& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object EncodedITSMessage that will be copied.
     */
    eProsima_user_DllExport EncodedITSMessage(
            EncodedITSMessage&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object EncodedITSMessage that will be copied.
     */
    eProsima_user_DllExport EncodedITSMessage& operator =(
            const EncodedITSMessage& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object EncodedITSMessage that will be copied.
     */
    eProsima_user_DllExport EncodedITSMessage& operator =(
            EncodedITSMessage&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x EncodedITSMessage object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const EncodedITSMessage& x) const;

    /*!
     * @brief Comparison operator.
     * @param x EncodedITSMessage object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const EncodedITSMessage& x) const;

    /*!
     * @brief This function copies the value in member topic
     * @param _topic New value to be copied in member topic
     */
    eProsima_user_DllExport void topic(
            const std::string& _topic);

    /*!
     * @brief This function moves the value in member topic
     * @param _topic New value to be moved in member topic
     */
    eProsima_user_DllExport void topic(
            std::string&& _topic);

    /*!
     * @brief This function returns a constant reference to member topic
     * @return Constant reference to member topic
     */
    eProsima_user_DllExport const std::string& topic() const;

    /*!
     * @brief This function returns a reference to member topic
     * @return Reference to member topic
     */
    eProsima_user_DllExport std::string& topic();
    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::vector<uint8_t>& _message);

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::vector<uint8_t>&& _message);

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::vector<uint8_t>& message() const;

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::vector<uint8_t>& message();
    /*!
     * @brief This function sets a value in member rssi
     * @param _rssi New value for member rssi
     */
    eProsima_user_DllExport void rssi(
            int16_t _rssi);

    /*!
     * @brief This function returns the value of member rssi
     * @return Value of member rssi
     */
    eProsima_user_DllExport int16_t rssi() const;

    /*!
     * @brief This function returns a reference to member rssi
     * @return Reference to member rssi
     */
    eProsima_user_DllExport int16_t& rssi();

    /*!
     * @brief This function sets a value in member newInfo
     * @param _newInfo New value for member newInfo
     */
    eProsima_user_DllExport void newInfo(
            bool _newInfo);

    /*!
     * @brief This function returns the value of member newInfo
     * @return Value of member newInfo
     */
    eProsima_user_DllExport bool newInfo() const;

    /*!
     * @brief This function returns a reference to member newInfo
     * @return Reference to member newInfo
     */
    eProsima_user_DllExport bool& newInfo();

    /*!
     * @brief This function sets a value in member packetSize
     * @param _packetSize New value for member packetSize
     */
    eProsima_user_DllExport void packetSize(
            int16_t _packetSize);

    /*!
     * @brief This function returns the value of member packetSize
     * @return Value of member packetSize
     */
    eProsima_user_DllExport int16_t packetSize() const;

    /*!
     * @brief This function returns a reference to member packetSize
     * @return Reference to member packetSize
     */
    eProsima_user_DllExport int16_t& packetSize();

    /*!
     * @brief This function sets a value in member stationID
     * @param _stationID New value for member stationID
     */
    eProsima_user_DllExport void stationID(
            int32_t _stationID);

    /*!
     * @brief This function returns the value of member stationID
     * @return Value of member stationID
     */
    eProsima_user_DllExport int32_t stationID() const;

    /*!
     * @brief This function returns a reference to member stationID
     * @return Reference to member stationID
     */
    eProsima_user_DllExport int32_t& stationID();

    /*!
     * @brief This function sets a value in member receiverID
     * @param _receiverID New value for member receiverID
     */
    eProsima_user_DllExport void receiverID(
            int32_t _receiverID);

    /*!
     * @brief This function returns the value of member receiverID
     * @return Value of member receiverID
     */
    eProsima_user_DllExport int32_t receiverID() const;

    /*!
     * @brief This function returns a reference to member receiverID
     * @return Reference to member receiverID
     */
    eProsima_user_DllExport int32_t& receiverID();

    /*!
     * @brief This function sets a value in member receiverType
     * @param _receiverType New value for member receiverType
     */
    eProsima_user_DllExport void receiverType(
            int16_t _receiverType);

    /*!
     * @brief This function returns the value of member receiverType
     * @return Value of member receiverType
     */
    eProsima_user_DllExport int16_t receiverType() const;

    /*!
     * @brief This function returns a reference to member receiverType
     * @return Reference to member receiverType
     */
    eProsima_user_DllExport int16_t& receiverType();

    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            double _timestamp);

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport double timestamp() const;

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport double& timestamp();

    /*!
     * @brief This function copies the value in member test
     * @param _test New value to be copied in member test
     */
    eProsima_user_DllExport void test(
            const std::string& _test);

    /*!
     * @brief This function moves the value in member test
     * @param _test New value to be moved in member test
     */
    eProsima_user_DllExport void test(
            std::string&& _test);

    /*!
     * @brief This function returns a constant reference to member test
     * @return Constant reference to member test
     */
    eProsima_user_DllExport const std::string& test() const;

    /*!
     * @brief This function returns a reference to member test
     * @return Reference to member test
     */
    eProsima_user_DllExport std::string& test();

    /*!
    * @brief This function returns the maximum serialized size of an object
    * depending on the buffer alignment.
    * @param current_alignment Buffer alignment.
    * @return Maximum serialized size.
    */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const EncodedITSMessage& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::string m_topic;
    std::vector<uint8_t> m_message;
    int16_t m_rssi;
    bool m_newInfo;
    int16_t m_packetSize;
    int32_t m_stationID;
    int32_t m_receiverID;
    int16_t m_receiverType;
    double m_timestamp;
    std::string m_test;

};

#endif // _FAST_DDS_GENERATED_ENCODEDITSMESSAGE_H_

