// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file EncodedITSMessage.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "EncodedITSMessage.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define EncodedITSMessage_max_cdr_typesize 652ULL;
#define EncodedITSMessage_max_key_cdr_typesize 0ULL;

EncodedITSMessage::EncodedITSMessage()
{
    // string m_topic
    m_topic ="";
    // sequence<octet> m_message

    // short m_rssi
    m_rssi = 0;
    // boolean m_newInfo
    m_newInfo = false;
    // short m_packetSize
    m_packetSize = 0;
    // long m_stationID
    m_stationID = 0;
    // long m_receiverID
    m_receiverID = 0;
    // short m_receiverType
    m_receiverType = 0;
    // double m_timestamp
    m_timestamp = 0.0;
    // string m_test
    m_test ="";

}

EncodedITSMessage::~EncodedITSMessage()
{










}

EncodedITSMessage::EncodedITSMessage(
        const EncodedITSMessage& x)
{
    m_topic = x.m_topic;
    m_message = x.m_message;
    m_rssi = x.m_rssi;
    m_newInfo = x.m_newInfo;
    m_packetSize = x.m_packetSize;
    m_stationID = x.m_stationID;
    m_receiverID = x.m_receiverID;
    m_receiverType = x.m_receiverType;
    m_timestamp = x.m_timestamp;
    m_test = x.m_test;
}

EncodedITSMessage::EncodedITSMessage(
        EncodedITSMessage&& x) noexcept 
{
    m_topic = std::move(x.m_topic);
    m_message = std::move(x.m_message);
    m_rssi = x.m_rssi;
    m_newInfo = x.m_newInfo;
    m_packetSize = x.m_packetSize;
    m_stationID = x.m_stationID;
    m_receiverID = x.m_receiverID;
    m_receiverType = x.m_receiverType;
    m_timestamp = x.m_timestamp;
    m_test = std::move(x.m_test);
}

EncodedITSMessage& EncodedITSMessage::operator =(
        const EncodedITSMessage& x)
{

    m_topic = x.m_topic;
    m_message = x.m_message;
    m_rssi = x.m_rssi;
    m_newInfo = x.m_newInfo;
    m_packetSize = x.m_packetSize;
    m_stationID = x.m_stationID;
    m_receiverID = x.m_receiverID;
    m_receiverType = x.m_receiverType;
    m_timestamp = x.m_timestamp;
    m_test = x.m_test;

    return *this;
}

EncodedITSMessage& EncodedITSMessage::operator =(
        EncodedITSMessage&& x) noexcept
{

    m_topic = std::move(x.m_topic);
    m_message = std::move(x.m_message);
    m_rssi = x.m_rssi;
    m_newInfo = x.m_newInfo;
    m_packetSize = x.m_packetSize;
    m_stationID = x.m_stationID;
    m_receiverID = x.m_receiverID;
    m_receiverType = x.m_receiverType;
    m_timestamp = x.m_timestamp;
    m_test = std::move(x.m_test);

    return *this;
}

bool EncodedITSMessage::operator ==(
        const EncodedITSMessage& x) const
{

    return (m_topic == x.m_topic && m_message == x.m_message && m_rssi == x.m_rssi && m_newInfo == x.m_newInfo && m_packetSize == x.m_packetSize && m_stationID == x.m_stationID && m_receiverID == x.m_receiverID && m_receiverType == x.m_receiverType && m_timestamp == x.m_timestamp && m_test == x.m_test);
}

bool EncodedITSMessage::operator !=(
        const EncodedITSMessage& x) const
{
    return !(*this == x);
}

size_t EncodedITSMessage::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return EncodedITSMessage_max_cdr_typesize;
}

size_t EncodedITSMessage::getCdrSerializedSize(
        const EncodedITSMessage& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.topic().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.message().size() > 0)
    {
        current_alignment += (data.message().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }



    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.test().size() + 1;


    return current_alignment - initial_alignment;
}

void EncodedITSMessage::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_topic.c_str();
    scdr << m_message;
    scdr << m_rssi;
    scdr << m_newInfo;
    scdr << m_packetSize;
    scdr << m_stationID;
    scdr << m_receiverID;
    scdr << m_receiverType;
    scdr << m_timestamp;
    scdr << m_test.c_str();

}

void EncodedITSMessage::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_topic;
    dcdr >> m_message;
    dcdr >> m_rssi;
    dcdr >> m_newInfo;
    dcdr >> m_packetSize;
    dcdr >> m_stationID;
    dcdr >> m_receiverID;
    dcdr >> m_receiverType;
    dcdr >> m_timestamp;
    dcdr >> m_test;
}

/*!
 * @brief This function copies the value in member topic
 * @param _topic New value to be copied in member topic
 */
void EncodedITSMessage::topic(
        const std::string& _topic)
{
    m_topic = _topic;
}

/*!
 * @brief This function moves the value in member topic
 * @param _topic New value to be moved in member topic
 */
void EncodedITSMessage::topic(
        std::string&& _topic)
{
    m_topic = std::move(_topic);
}

/*!
 * @brief This function returns a constant reference to member topic
 * @return Constant reference to member topic
 */
const std::string& EncodedITSMessage::topic() const
{
    return m_topic;
}

/*!
 * @brief This function returns a reference to member topic
 * @return Reference to member topic
 */
std::string& EncodedITSMessage::topic()
{
    return m_topic;
}
/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void EncodedITSMessage::message(
        const std::vector<uint8_t>& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void EncodedITSMessage::message(
        std::vector<uint8_t>&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::vector<uint8_t>& EncodedITSMessage::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::vector<uint8_t>& EncodedITSMessage::message()
{
    return m_message;
}
/*!
 * @brief This function sets a value in member rssi
 * @param _rssi New value for member rssi
 */
void EncodedITSMessage::rssi(
        int16_t _rssi)
{
    m_rssi = _rssi;
}

/*!
 * @brief This function returns the value of member rssi
 * @return Value of member rssi
 */
int16_t EncodedITSMessage::rssi() const
{
    return m_rssi;
}

/*!
 * @brief This function returns a reference to member rssi
 * @return Reference to member rssi
 */
int16_t& EncodedITSMessage::rssi()
{
    return m_rssi;
}

/*!
 * @brief This function sets a value in member newInfo
 * @param _newInfo New value for member newInfo
 */
void EncodedITSMessage::newInfo(
        bool _newInfo)
{
    m_newInfo = _newInfo;
}

/*!
 * @brief This function returns the value of member newInfo
 * @return Value of member newInfo
 */
bool EncodedITSMessage::newInfo() const
{
    return m_newInfo;
}

/*!
 * @brief This function returns a reference to member newInfo
 * @return Reference to member newInfo
 */
bool& EncodedITSMessage::newInfo()
{
    return m_newInfo;
}

/*!
 * @brief This function sets a value in member packetSize
 * @param _packetSize New value for member packetSize
 */
void EncodedITSMessage::packetSize(
        int16_t _packetSize)
{
    m_packetSize = _packetSize;
}

/*!
 * @brief This function returns the value of member packetSize
 * @return Value of member packetSize
 */
int16_t EncodedITSMessage::packetSize() const
{
    return m_packetSize;
}

/*!
 * @brief This function returns a reference to member packetSize
 * @return Reference to member packetSize
 */
int16_t& EncodedITSMessage::packetSize()
{
    return m_packetSize;
}

/*!
 * @brief This function sets a value in member stationID
 * @param _stationID New value for member stationID
 */
void EncodedITSMessage::stationID(
        int32_t _stationID)
{
    m_stationID = _stationID;
}

/*!
 * @brief This function returns the value of member stationID
 * @return Value of member stationID
 */
int32_t EncodedITSMessage::stationID() const
{
    return m_stationID;
}

/*!
 * @brief This function returns a reference to member stationID
 * @return Reference to member stationID
 */
int32_t& EncodedITSMessage::stationID()
{
    return m_stationID;
}

/*!
 * @brief This function sets a value in member receiverID
 * @param _receiverID New value for member receiverID
 */
void EncodedITSMessage::receiverID(
        int32_t _receiverID)
{
    m_receiverID = _receiverID;
}

/*!
 * @brief This function returns the value of member receiverID
 * @return Value of member receiverID
 */
int32_t EncodedITSMessage::receiverID() const
{
    return m_receiverID;
}

/*!
 * @brief This function returns a reference to member receiverID
 * @return Reference to member receiverID
 */
int32_t& EncodedITSMessage::receiverID()
{
    return m_receiverID;
}

/*!
 * @brief This function sets a value in member receiverType
 * @param _receiverType New value for member receiverType
 */
void EncodedITSMessage::receiverType(
        int16_t _receiverType)
{
    m_receiverType = _receiverType;
}

/*!
 * @brief This function returns the value of member receiverType
 * @return Value of member receiverType
 */
int16_t EncodedITSMessage::receiverType() const
{
    return m_receiverType;
}

/*!
 * @brief This function returns a reference to member receiverType
 * @return Reference to member receiverType
 */
int16_t& EncodedITSMessage::receiverType()
{
    return m_receiverType;
}

/*!
 * @brief This function sets a value in member timestamp
 * @param _timestamp New value for member timestamp
 */
void EncodedITSMessage::timestamp(
        double _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function returns the value of member timestamp
 * @return Value of member timestamp
 */
double EncodedITSMessage::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
double& EncodedITSMessage::timestamp()
{
    return m_timestamp;
}

/*!
 * @brief This function copies the value in member test
 * @param _test New value to be copied in member test
 */
void EncodedITSMessage::test(
        const std::string& _test)
{
    m_test = _test;
}

/*!
 * @brief This function moves the value in member test
 * @param _test New value to be moved in member test
 */
void EncodedITSMessage::test(
        std::string&& _test)
{
    m_test = std::move(_test);
}

/*!
 * @brief This function returns a constant reference to member test
 * @return Constant reference to member test
 */
const std::string& EncodedITSMessage::test() const
{
    return m_test;
}

/*!
 * @brief This function returns a reference to member test
 * @return Reference to member test
 */
std::string& EncodedITSMessage::test()
{
    return m_test;
}


size_t EncodedITSMessage::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return EncodedITSMessage_max_key_cdr_typesize;
}

bool EncodedITSMessage::isKeyDefined()
{
    return false;
}

void EncodedITSMessage::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

