---
# defaults file for cps role
generation_enable: true
processing_enable: true

bike_adapter_enable: false
autoware_adapter_enable: false

# 0 = disabled; N = one adapter subscribing to N topics (jetson/camera/1/..., ..., jetson/camera/N/...)
camera_adapter_num_topics: 0
# 0 = disabled; 1 = one radar adapter (only 1 makes sense)
radar_adapter_num_topics: 0

# If you want to “clean up” /services/cps first, set true,
# otherwise the directory is left intact and compose will pick up existing files.
clean_up: true

image_tag: latest
docker_registry: code.nap.av.it.pt:5050/mobility-networks/cps-v2

# For camera-adapter: base prefix
camera_adapter_mqtt_topic_base: "jetson/camera"
# For radar-adapter:
radar_adapter_mqtt_topic: "jetson/radar-plus"

# For bike-adapter:
bike_adapter_mqtt_topic: "rpi/cam_detections"

cps_configs:
  generation:
    debug: false
    prometheus: true
    prometheus_port: 9102
    domain_id: "{{ id }}"
    station_type: "{{ station_type }}"
    station_latitude: "{{ locator_latitude }}"
    station_longitude: "{{ locator_longitude }}"
    location_provider: static   # or “dds” or “mqtt”; override in host_vars if needed
    mqtt_host: ""       # if location_provider=mqtt
    mqtt_port: ""       # if location_provider=mqtt
    mqtt_topic: ""      # if location_provider=mqtt
    dds_topic: ""       # if location_provider=dds
    max_objects: -1
    interval: 100
    performance_logs: false
    generation_dds_topic: "cps-v2/in/cpm"  # or "vanetza/in/cpm"
    max_object_age: 2
    clean_interval: 1
    ignore_rules: false
    priority: "etsi"
    zenoh_endpoint: 127.0.0.1
    add_pending_objects: false
    mqtt_debug: false  # Set to true to enable MQTT debug CPMs on mqtt/in/cpm

  processing: # Mostly used for ATCLL visualization
    debug: false
    prometheus: true
    prometheus_port: 9103
    domain_id: "{{ id }}"
    station_type: "{{ station_type }}"
    station_id: "{{ id }}"
    repeat_id_interval: 3600
    performance_logs: false
    location_provider: "static"  # or “dds” or “mqtt”; override in host_vars if needed
    mqtt_host: ""       # if location_provider=mqtt
    mqtt_port: ""       # if location_provider=mqtt
    mqtt_topic: ""      # if location_provider=mqtt
    dds_topic: ""       # if location_provider=dds
    dds_output_topic: "objects"
    local_mqtt_enable_publisher: true
    local_mqtt_host: 127.0.0.1
    local_mqtt_port: 1883
    local_mqtt_output_topic: "objects"
    remote_mqtt_enable_publisher: false
    remote_mqtt_host: "atcll-services.nap.av.it.pt"
    remote_mqtt_port: 1884
    remote_mqtt_username: "atcll-services"
    remote_mqtt_password: "bWAoaB&6kQ#pjE9@Dv2opvjDiyxKsw"
    remote_mqtt_output_topic: "{{ processing_remote_prefix }}"
    zenoh_endpoint: 127.0.0.1
    zenoh_output_topic: "objects"

  "radar-adapter":
    debug: false
    domain_id: "{{ id }}"
    mqtt_host: 127.0.0.1
    mqtt_port: 1883
    mqtt_topics: "{{ radar_adapter_mqtt_topic }}"
    mqtt_client_id: "radar-adapter"

  "camera-adapter":
    debug: false
    domain_id: "{{ id }}"
    mqtt_host: 127.0.0.1
    mqtt_port: 1883
    mqtt_topics: "{{ camera_adapter_mqtt_topics }}"
    mqtt_client_id: "camera-adapter"

  "bike-adapter":
    debug: false
    domain_id: "{{ id }}"
    mqtt_host: 127.0.0.1
    mqtt_port: 1883
    mqtt_topic: "{{ bike_adapter_mqtt_topic }}"
    mqtt_client_id: "bike-adapter"

  "autoware-adapter":
    debug: false
    domain_id: "{{ id }}"
