services:
            
  generation:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/generation:v1.0.3
    restart: always
    volumes:
      - /services/cps/generation/config.ini:/config.ini
      - ./logs:/logs
    network_mode: host
    ipc: host
    
  processing:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/processing:v1.0.5
    restart: always
    volumes:
      - /services/cps/processing/config.ini:/config.ini
      - ./logs:/logs
    network_mode: host
    ipc: host