services:
  camera-adapter:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/camera-adapter:latest
    restart: always
    volumes:
      - /services/cps/camera-adapter/config.ini:/config.ini
    network_mode: host
    ipc: host
    
            
  camera-adapter2:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/camera-adapter:latest
    restart: always
    volumes:
      - /services/cps/camera-adapter2/config.ini:/config.ini
    network_mode: host
    ipc: host
    
            
  camera-adapter3:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/camera-adapter:latest
    restart: always
    volumes:
      - /services/cps/camera-adapter3/config.ini:/config.ini
    network_mode: host
    ipc: host
    
            
  camera-adapter4:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/camera-adapter:latest
    restart: always
    volumes:
      - /services/cps/camera-adapter4/config.ini:/config.ini
    network_mode: host
    ipc: host
