services:

  generation:
    image: code.nap.av.it.pt:5050/mobility-networks/its-perception-service/generation:latest
    restart: always
    volumes:
      - /services/cps/generation/config.ini:/config.ini
      - ./logs:/logs
    network_mode: host
    ipc: host
    
  processing:
    image: code.nap.av.it.pt:5050/mobility-networks/its-perception-service/processing:latest
    restart: always
    volumes:
      - /services/cps/processing/config.ini:/config.ini
      - ./logs:/logs
    network_mode: host
    ipc: host

  radar-adapter:
    image: code.nap.av.it.pt:5050/mobility-networks/its-perception-service/radar-adapter:latest
    restart: always
    volumes:
      - /services/cps/radar-adapter/config.ini:/config.ini
    network_mode: host
    ipc: host