services:

  radar-adapter:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/radar-adapter:latest
    restart: always
    volumes:
      - ./radar-adapter/config.ini:/config.ini
    network_mode: host
    ipc: host