version: '2.4'

services:
  vortex_adapter:
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/vortex-adapter:fix
    container_name: vortex_adapter
    volumes:
      - ./config.ini:/vortex_adapter/config.ini
      - ./start.sh:/start.sh
    network_mode: host
    ipc: host
    command: ["/bin/bash", "-c" , "/start.sh"]
    tty: true
