version: '2.4'
services:
  cpm-generation:
    hostname: cpm-generation
    container_name: cpm-generation
    image: code.nap.av.it.pt:5050/mobility-networks/cps-v2/generation:dev
    volumes:
      - ./config.ini:/config.ini
      - ./logs:/logs
    network_mode: host
    ipc: host
