global:
  scrape_interval: 2s

scrape_configs:
  - job_name: cps
    static_configs:
      - targets: 
          - atcll-p33-rpi.nap.av.it.pt:9102
          - atcll-p33-rpi.nap.av.it.pt:9103
        labels:
          post_id: "33"
          location: "Rua Doutor Mário Sacramento"